server:
  port: 9010

spring:
  application:
    name: epms

  datasource:
    url: jdbc:postgresql://43.205.24.208:5432/epms
    username: postgres
    password: pgadmin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

file:
  encryption:
    simpleEncSecret: 8F3dK9@Q!2zL7X#A
